import { chromium } from 'playwright';
import { writeFileSync } from 'fs';
import { join } from 'path';
import { fileURLToPath } from 'url';
import { dirname } from 'path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const projectRoot = join(__dirname, '..');

async function generatePDFWithContent() {
  console.log('🚀 Generating PDF with full content rendering...');
  
  const browser = await chromium.launch();
  const page = await browser.newPage();
  
  // Navigate to the generate-pdf.html file
  const htmlPath = `file://${join(projectRoot, 'generate-pdf.html')}`;
  await page.goto(htmlPath);
  
  console.log('📄 Loaded HTML file, waiting for libraries to load...');
  await page.waitForTimeout(2000);
  
  // Wait for the document element to be ready
  await page.waitForSelector('#electrical-quote-document', { state: 'attached' });
  
  // Make the document visible for rendering
  await page.evaluate(() => {
    const doc = document.getElementById('electrical-quote-document');
    if (doc) {
      doc.classList.remove('hidden');
      doc.style.display = 'block';
      doc.style.visibility = 'visible';
    }
  });
  
  // Click the generate button
  console.log('🖱️  Clicking generate button...');
  await page.click('button:has-text("Generar PDF")');
  
  // Wait for PDF generation to complete
  console.log('⏳ Waiting for PDF generation (this may take 10-15 seconds)...');
  
  // Wait for the success message
  await page.waitForSelector('#status:has-text("PDF generado exitosamente")', { timeout: 30000 });
  
  const statusText = await page.textContent('#status');
  console.log('📊 Status:', statusText);
  
  // Get the PDF data from the page (if available)
  const pdfData = await page.evaluate(() => {
    return (window as any).pdfData || null;
  });
  
  if (pdfData) {
    // Save the PDF if we have the data
    const timestamp = new Date().toISOString().split('T')[0];
    const filename = `proyecto-electrico-rendered-${timestamp}.pdf`;
    const outputPath = join(projectRoot, filename);
    
    // Convert base64 to buffer
    const buffer = Buffer.from(pdfData.split(',')[1], 'base64');
    writeFileSync(outputPath, buffer);
    
    console.log('✅ PDF generated successfully with rendered content!');
    console.log('📁 Saved to:', outputPath);
    console.log('📊 File size:', (buffer.length / 1024).toFixed(2), 'KB');
  } else {
    console.log('ℹ️  PDF was generated by the browser (check Downloads folder)');
    console.log('📊 Status:', statusText);
  }
  
  // Also generate a PDF using Playwright's built-in method as backup
  console.log('📑 Generating backup PDF using Playwright...');
  const pdfBuffer = await page.pdf({
    format: 'A4',
    margin: {
      top: '10mm',
      right: '10mm',
      bottom: '10mm',
      left: '10mm'
    },
    printBackground: true
  });
  
  const timestamp = new Date().toISOString().split('T')[0];
  const backupFilename = `proyecto-electrico-backup-${timestamp}.pdf`;
  const backupPath = join(projectRoot, backupFilename);
  
  writeFileSync(backupPath, pdfBuffer);
  console.log('✅ Backup PDF saved to:', backupPath);
  console.log('📊 Backup file size:', (pdfBuffer.length / 1024).toFixed(2), 'KB');
  
  await browser.close();
  
  return { pdfData, backupPath };
}

generatePDFWithContent().catch(console.error);

